//assigning actions to strings

export default {
    SET_ENCOUNTER_PENDING: 'SET_ENCOUNTER_PENDING',
    SET_ENCOUNTER_SUCCESS: 'SET_ENCOUNTER_SUCCESS',
    ADD_ENCOUNTER_PENDING: 'ADD_ENCOUNTER_PENDING',
    ADD_ENCOUNTER_SUCCESS: 'ADD_ENCOUNTER_SUCCESS',
    REMOVE_ENCOUNTER_PENDING: 'REMOVE_ENCOUNTER_PENDING',
    REMOVE_ENCOUNTER_SUCCESS: 'REMOVE_ENCOUNTER_SUCCESS',
    UPDATE_ENCOUNTER_PENDING: 'UPDATE_ENCOUNTER_PENDING',
    UPDATE_ENCOUNTER_SUCCESS: 'UPDATE_ENCOUNTER_SUCCESS'
};