//assigning actions to strings

export default {
    SET_PATIENT_PENDING: 'SET_PATIENT_PENDING',
    SET_PATIENT_SUCCESS: 'SET_PATIENT_SUCCESS',
    ADD_PATIENT_PENDING: 'ADD_PATIENT_PENDING',
    ADD_PATIENT_SUCCESS: 'ADD_PATIENT_SUCCESS',
    REMOVE_PATIENT_PENDING: 'REMOVE_PATIENT_PENDING',
    REMOVE_PATIENT_SUCCESS: 'REMOVE_PATIENT_SUCCESS',
    UPDATE_PATIENT_PENDING: 'UPDATE_PATIENT_PENDING',
    UPDATE_PATIENT_SUCCESS: 'UPDATE_PATIENT_SUCCESS',

    REDIRECT_PENDING: 'REDIRECT_PENDING',
    REDIRECT_SUCCESS: 'REDIRECT_SUCCESS',
    REDIRECT_BACK_PENDING: 'REDIRECT_BACK_PENDING',
    REDIRECT_BACK_SUCCESS: 'REDIRECT_BACK_SUCCESS',

    SET_ERROR_PENDING: 'SET_ERROR_PENDING',
    SET_ERROR_SUCCESS: 'SET_ERROR_SUCCESS',
    SET_NETWORK_ERROR_PENDING: 'SET_ERROR_PENDING',
    SET_NETWORK_ERROR_SUCCESS: 'SET_ERROR_SUCCESS'
};